#!/bin/bash

echo '===================================================================='
# confirm directory exists
mkdir -p /var/www/html/pub/epel
# cd
cd /var/www/html/pub/epel
# echo working directory
echo 'updating '$(pwd)
# rsync nb: epel is not available from ftp.iinet
rsync -avh --progress --delete --exclude={"4*","5*","6*","testing*","7/SRPMS*","7/aarch*","7/ppc*","7/x86_64/debug*"} rsync://mirror.aarnet.edu.au/pub/epel/ .
# chcon
chcon -R -t httpd_sys_content_t /var/www/html/pub/epel

echo '===================================================================='
